using System.IO;

namespace VCI
{
    internal static class VciVersionPackageJsonWriter
    {
        private const string FilePath = "Assets/VCI/package.json";

        public static void Write(int majorVersion, int minorVersion, int patchVersion)
        {
            File.WriteAllText(FilePath, GenerateFileText(majorVersion, minorVersion, patchVersion));
        }

        private static string GenerateFileText(int majorVersion, int minorVersion, int patchVersion)
        {
            // TODO: UPM API から引っ張ってきたい.
            var dependentUniVrmVersion = "0.99.0";

            return $@"{{
  ""//"": ""Don't modify. This file is generated by '{nameof(VciVersionPackageJsonWriter)}' class."",
  ""name"": ""com.virtualcast.univci"",
  ""version"": ""{majorVersion}.{minorVersion}.{patchVersion}"",
  ""displayName"": ""VCI"",
  ""description"": ""VCI Exporter"",
  ""unity"": ""2020.3"",
  ""keywords"": [""vci"",""vr""],
  ""author"": {{
    ""name"": ""VirtualCast, Inc.""
  }},
  ""dependencies"": {{
    ""com.vrmc.vrm"": ""{dependentUniVrmVersion}"",
    ""com.vrmc.univrm"": ""{dependentUniVrmVersion}"",
    ""com.vrmc.vrmshaders"": ""{dependentUniVrmVersion}"",
    ""com.vrmc.gltf"": ""{dependentUniVrmVersion}""
  }}
}}";
        }
    }
}
