//
// NOTE: Don't modify.
//       This file is generated by 'VciVersionClassWriter' class.
//
namespace VCI
{
    public static class VCIVersion
    {
        public const string VCI_VERSION = "UniVCI-" + VERSION;

        public const int MAJOR = 0;
        public const int MINOR = 35;
        public const int PATCH = 0;

        public const string VERSION = "0.35";
        public const string PATCH_NUMBER = "0";
    }
}
