
namespace VCI
{
    public static partial class VCIVersion
    {
        // this is generated by UniVCI/Increment|Decrement menu

        public const int MAJOR = 0;
        public const int MINOR = 29;

        public const string VERSION = "0.29";
    }
}
