//
// NOTE: Don't modify.
//       This file is generated by 'VciVersionClassWriter' class.
//
namespace VCI
{
    public static class VCIVersion
    {
        public const string VCI_VERSION = "UniVCI-" + VERSION;

        public const int MAJOR = 0;
        public const int MINOR = 39;
        public const int PATCH = 1;

        public const string VERSION = "0.39";
        public const string PATCH_NUMBER = "1";
    }
}
