using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UniGLTF;
using UniJSON;

namespace VCI
{
    public static class VCIVersionMenu
    {
        private const string path = "Assets/VCI/UniVCI/Scripts/Format/VCIVersion.cs";
        private const string IncrementVersionMenuName = Constants.DevelopMenuPrefix + "/IncrementVersion";
        private const string DecrementVersionMenuName = Constants.DevelopMenuPrefix + "/DecrementVersion";
        private const string IncrementPatchMenuName = Constants.DevelopMenuPrefix + "/IncrementPatch";
        private const string DecrementPatchMenuName = Constants.DevelopMenuPrefix + "/DecrementPatch";
        private const string VersionMenuName = Constants.MenuPrefix + "/Version: " + VCIVersion.VCI_VERSION + "." + VCIVersion.PATCH_NUMBER;

        private const string template = @"
namespace VCI
{{
    public static partial class VCIVersion
    {{
        // this is generated by UniVCI/Increment|Decrement menu

        public const int MAJOR = {0};
        public const int MINOR = {1};
        public const int PATCH = {2};

        public const string VERSION = ""{0}.{1}"";
        public const string PATCH_NUMBER = ""{2}"";
    }}
}}
";

        [MenuItem(VersionMenuName, priority = int.MaxValue)]
        private static void VersionMenu() { }

        [MenuItem(VersionMenuName, true)]
        private static bool VersionMenuValidation() { return false; }

#if VCI_DEVELOP
        [MenuItem(IncrementVersionMenuName)]
#endif
        private static void IncrementVersion()
        {
            var source = string.Format(template, VCIVersion.MAJOR, VCIVersion.MINOR + 1, 0);
            File.WriteAllText(path, source);
            AssetDatabase.Refresh();
        }

#if VCI_DEVELOP
        [MenuItem(DecrementVersionMenuName)]
#endif
        private static void DecrementVersion()
        {
            var source = string.Format(template, VCIVersion.MAJOR, VCIVersion.MINOR - 1, 0);
            File.WriteAllText(path, source);
            AssetDatabase.Refresh();
        }

#if VCI_DEVELOP
        [MenuItem(IncrementPatchMenuName)]
#endif
        private static void IncrementPatch()
        {
            var source = string.Format(template, VCIVersion.MAJOR, VCIVersion.MINOR, VCIVersion.PATCH + 1);
            File.WriteAllText(path, source);
            AssetDatabase.Refresh();
        }

#if VCI_DEVELOP
        [MenuItem(DecrementPatchMenuName)]
#endif
        private static void DecrementPatch()
        {
            var source = string.Format(template, VCIVersion.MAJOR, VCIVersion.MINOR, VCIVersion.PATCH - 1);
            File.WriteAllText(path, source);
            AssetDatabase.Refresh();
        }

        private static string GetTitle(JsonNode node)
        {
            try
            {
                var titleNode = node["title"];
                if (titleNode.IsString()) return titleNode.GetString();
            }
            catch (Exception) { }

            return "";
        }

        private static void TraverseItem(JsonNode node, JsonFormatter f, FilePath dir)
        {
            var title = GetTitle(node);
            if (string.IsNullOrEmpty(title))
            {
                Traverse(node, f, dir);
            }
            else
            {
                // ref
                f.BeginMap();
                f.Key("$ref");
                var fileName = string.Format("{0}.schema.json", title);
                f.Value(fileName);
                f.EndMap();

                // new formatter
                {
                    var subFormatter = new JsonFormatter(4);

                    subFormatter.BeginMap();
                    foreach (var _kv in node.ObjectItems())
                    {
                        subFormatter.Key(_kv.Key.GetUtf8String());
                        Traverse(_kv.Value, subFormatter, dir);
                    }

                    subFormatter.EndMap();

                    var subJson = subFormatter.ToString();
                    var path = dir.Child(fileName);
                    File.WriteAllText(path.FullPath, subJson);
                }
            }
        }

        private static void Traverse(JsonNode node, JsonFormatter f, FilePath dir)
        {
            if (node.IsArray())
            {
                f.BeginList();
                foreach (var x in node.ArrayItems()) TraverseItem(x, f, dir);
                f.EndList();
            }
            else if (node.IsMap())
            {
                f.BeginMap();
                foreach (var kv in node.ObjectItems())
                {
                    f.Key(kv.Key.GetUtf8String());
                    TraverseItem(kv.Value, f, dir);
                }

                f.EndMap();
            }
            else
            {
                f.Value(node);
            }
        }

        private struct FilePath
        {
            public string FullPath { get; private set; }

            public FilePath(string path)
            {
                FullPath = Path.GetFullPath(path).Replace("\\", "/");
            }

            public void EnsureFolder()
            {
                Debug.LogFormat("EnsureFolder: {0}", FullPath);
                var splited = FullPath.Split('/');
                for (var i = 0; i < splited.Length; ++i)
                {
                    var path = String.Join("/", splited.Take(i + 1).ToArray());
                    if (!Directory.Exists(path))
                    {
                        Debug.LogFormat("CreateDirectory: {0}", path);
                        Directory.CreateDirectory(path);
                    }
                }
            }

            public FilePath Child(string name)
            {
                return new FilePath(Path.Combine(FullPath, name));
            }
        }

        private static FilePath SplitAndWriteJson(JsonNode parsed, FilePath dir, string name)
        {
            var f = new JsonFormatter(4);
            Traverse(parsed, f, dir);
            var json = f.ToString();

            var path = dir.Child(string.Format("{0}.schema.json", name));
            Debug.LogFormat("write JsonSchema: {0}", path.FullPath);
            File.WriteAllText(path.FullPath, json);
            return path;
        }
    }
}
